import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateUser1715028537217 implements MigrationInterface {
  name = 'CreateUser1715028537217';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "EPS_NESTJS_ROLE" ("id" integer NOT NULL, "name" VARCHAR2(255) NOT NULL, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "EPS_NESTJS_STATUS" ("id" integer NOT NULL, "name" VARCHAR2(255) NOT NULL, CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "EPS_NESTJS_FILE" ("id" VARCHAR(36) NOT NULL, "path" VARCHAR2(512) NOT NULL, CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "EPS_NESTJS_USER" ("id" integer GENERATED BY DEFAULT AS IDENTITY, "email"  VARCHAR2(255), "password"  VARCHAR2(255), "provider" VARCHAR2(255) DEFAULT 'email' NOT NULL, "socialId"  VARCHAR2(255), "firstName"  VARCHAR2(255),"lastName"  VARCHAR2(255), "createdAt" TIMESTAMP DEFAULT SYSDATE NOT NULL, "updatedAt" TIMESTAMP DEFAULT SYSDATE NOT NULL, "deletedAt" TIMESTAMP, "photoId" VARCHAR(36), "roleId" integer, "statusId" integer, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "REL_75e2be4ce11d447ef43be0e374" UNIQUE ("photoId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "IDX_9bd2fe7a8e694dedc4ec2f666f" ON "EPS_NESTJS_USER" ("socialId") `);
    await queryRunner.query(`CREATE INDEX "IDX_58e4dbff0e1a32a9bdc861bb29" ON "EPS_NESTJS_USER" ("firstName") `);
    await queryRunner.query(`CREATE INDEX "IDX_f0e1b4ecdca13b177e2e3a0613" ON "EPS_NESTJS_USER" ("lastName") `);
    await queryRunner.query(
      `CREATE TABLE "EPS_NESTJS_SESSION" ("id" integer GENERATED BY DEFAULT AS IDENTITY, "hash" VARCHAR2(255) NOT NULL, "createdAt" TIMESTAMP DEFAULT SYSDATE NOT NULL, "updatedAt" TIMESTAMP DEFAULT SYSDATE NOT NULL, "deletedAt" TIMESTAMP, "userId" integer, CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "IDX_3d2f174ef04fb312fdebd0ddc5" ON "EPS_NESTJS_SESSION" ("userId") `);
    await queryRunner.query(
      `ALTER TABLE "EPS_NESTJS_USER" ADD CONSTRAINT "FK_75e2be4ce11d447ef43be0e374f" FOREIGN KEY ("photoId") REFERENCES "EPS_NESTJS_FILE" ("id")`,
    );
    await queryRunner.query(
      `ALTER TABLE "EPS_NESTJS_USER" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "EPS_NESTJS_ROLE" ("id")`,
    );
    await queryRunner.query(
      `ALTER TABLE "EPS_NESTJS_USER" ADD CONSTRAINT "FK_dc18daa696860586ba4667a9d31" FOREIGN KEY ("statusId") REFERENCES "EPS_NESTJS_STATUS" ("id")`,
    );
    await queryRunner.query(
      `ALTER TABLE "EPS_NESTJS_SESSION" ADD CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53" FOREIGN KEY ("userId") REFERENCES "EPS_NESTJS_USER" ("id")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // await queryRunner.query(
    //   `ALTER TABLE "EPS_NESTJS_SESSION" DROP CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53"`,
    // );
    // await queryRunner.query(
    //   `ALTER TABLE "EPS_NESTJS_USER" DROP CONSTRAINT "FK_dc18daa696860586ba4667a9d31"`,
    // );
    // await queryRunner.query(
    //   `ALTER TABLE "EPS_NESTJS_USER" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`,
    // );
    // await queryRunner.query(
    //   `ALTER TABLE "EPS_NESTJS_USER" DROP CONSTRAINT "FK_75e2be4ce11d447ef43be0e374f"`,
    // );
    // await queryRunner.query(
    //   `DROP INDEX "public"."IDX_3d2f174ef04fb312fdebd0ddc5"`,
    // );
    await queryRunner.query(`DROP TABLE "EPS_NESTJS_SESSION" CASCADE CONSTRAINTS`);
    // await queryRunner.query(
    //   `DROP INDEX "public"."IDX_f0e1b4ecdca13b177e2e3a0613"`,
    // );
    // await queryRunner.query(
    //   `DROP INDEX "public"."IDX_58e4dbff0e1a32a9bdc861bb29"`,
    // );
    // await queryRunner.query(
    //   `DROP INDEX "public"."IDX_9bd2fe7a8e694dedc4ec2f666f"`,
    // );
    await queryRunner.query(`DROP TABLE "EPS_NESTJS_USER" CASCADE CONSTRAINTS`);
    await queryRunner.query(`DROP TABLE "EPS_NESTJS_FILE" CASCADE CONSTRAINTS`);
    await queryRunner.query(`DROP TABLE "EPS_NESTJS_STATUS" CASCADE CONSTRAINTS`);
    await queryRunner.query(`DROP TABLE "EPS_NESTJS_ROLE" CASCADE CONSTRAINTS`);
  }
}
