import { MigrationInterface, QueryRunner } from 'typeorm';

export class EPSNESTJSARTICOLICOSTICFCOMM1741600691122 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "EPS_NESTJS_ARTICOLI_COSTI_CF_COMM" (
        "TIPO_TRASFERTA" varchar2(100), 
        "COD_ART" varchar2(20), 
        "CF_COMM_ID" VARCHAR2(20) NOT NULL, 
        "id" number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
        "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, 
        "updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "EPS_NESTJS_ARTICOLI_COSTI_CF_COMM"`);
  }
}
