import { MigrationInterface, QueryRunner } from 'typeorm';

export class EPSNESTJSARTICOLICOSTICF1741600749218
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "EPS_NESTJS_ARTICOLI_COSTI_CF" ("TIPO_TRASFERTA" varchar2(100), "COD_ART" varchar2(20), "COD_CF" VARCHAR2(12) NOT NULL, "id" number GENERATED BY DEFAULT AS IDENTITY, "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_00e7b3e138034694c6120a79ddd" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "EPS_NESTJS_ARTICOLI_COSTI_CF"`);
  }
}
