import { MigrationInterface, QueryRunner } from 'typeorm';

export class EPSNESTJSORPEFFCICLIESEC1742816354323
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE EPS_NESTJS_ORP_EFF_CICLI_ESEC ADD "id" integer GENERATED BY DEFAULT AS IDENTITY`,
    );
    await queryRunner.query(
      `ALTER TABLE EPS_NESTJS_ORP_EFF_CICLI_ESEC ADD "createdAt" TIMESTAMP DEFAULT SYSDATE NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE EPS_NESTJS_ORP_EFF_CICLI_ESEC ADD "updatedAt" TIMESTAMP DEFAULT SYSDATE NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE EPS_NESTJS_ORP_EFF_CICLI_ESEC ADD "deletedAt" TIMESTAMP`,
    );
    await queryRunner.query(
      `ALTER TABLE EPS_NESTJS_ORP_EFF_CICLI_ESEC ADD CONSTRAINT "PK_f55da76ac1c3ac420f444d2fa22" PRIMARY KEY ("id")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE EPS_NESTJS_ORP_EFF_CICLI_ESEC DROP COLUMN "id", "createdAt", "updatedAt", "deletedAt"`,
    );
    await queryRunner.query(
      `ALTER TABLE EPS_NESTJS_ORP_EFF_CICLI_ESEC DROP CONSTRAINT PK_f55da76ac1c3ac420f444d2fa22`,
    );
  }
}
