import { MigrationInterface, QueryRunner } from 'typeorm';

export class EPSNESTJSTARGAMEZZI1743409188847 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "EPS_NESTJS_TARGA_MEZZI" (
        "COD_ART" VARCHAR2(20), 
        "id" number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
        "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, 
        "updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
      )`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "EPS_NESTJS_TARGA_MEZZI"`);
  }
}
