import { MigrationInterface, QueryRunner } from 'typeorm';

export class EPSNESTJSDESTINAZIONI1744223008524 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE EPS_NESTJS_DESTINAZIONI(
        "LINK" VARCHAR2(2000 BYTE), 
        "KM" VARCHAR2(50 BYTE),
        "VALUE" NUMBER(16,0),
        "RESPONSE" VARCHAR2(4000 BYTE),
        "id" number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
        "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, 
        "updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL)
        `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "EPS_NESTJS_DESTINAZIONI"`);
  }
}
