SELECT
    OP.SERIE_DOC,
    X1.CODICE2,
    OFC.DES_LAV,
    OFC.DOC_RIGA_ID,
    OCR.DES_RIGA,
    OCR.COD_ART,
    TO_CHAR(OCR.DATA_DOC, 'YY')
    || X1.CODICE2
    || OP.NUM_DOC
    || '-'
    || OFC.NUM_RIGA,
 
    -- OFCE.DATA_INIZIO,
    -- OFCE.DATA_FINE,
    OFCE.TEMPO_OPERATORE,
    OFC.*,
    LOO.*,
    OFCE.*
FROM
    ORP_EFF_CICLI      OFC
    LEFT JOIN LINK_ORP_ORD LOO
    ON LOO.ORP_EFF_DOC_ID = OFC.DOC_ID
    LEFT JOIN ORD_CLI_RIGHE OCR
    ON OCR.DOC_RIGA_ID = LOO.ORD_CLI_DOC_RIGA_ID
    LEFT JOIN ORP_EFF_CICLI_ESEC OFCE
    ON OFCE.DOC_RIGA_ID = OFC.DOC_RIGA_ID
    INNER JOIN ORP_EFF OP
    ON OP.DOC_ID = OFC.DOC_ID
    INNER JOIN X1_TRAS_CODICI X1
    ON X1.CODICE1 = OP.SERIE_DOC
WHERE
 
    --    OFC.DOC_ID = '2024-OP-0004020'
    --AND
    TO_CHAR(OCR.DATA_DOC, 'YY')
    || X1.CODICE2
    || OP.NUM_DOC
    || '-'
    || OFC.NUM_RIGA = '2414019-1'